# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'day09' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'ttarsha2021', :git => 'https://github.com/LidiaGr/Swift_piscine.git'
  # Pods for day09

end
